### ISSUE TITLE
App location

### ISSUE THREAD

**Issue by Scit** [cdriehuys/ansible-role-django-app#2]
Why do we pull our App (app_repo) from git repo instead of using local source code?

**Comment by cdriehuys** [comment]
Sorry for the delayed response. I decided to pull from the repo to make it easier to avoid deploying uncommitted code, and to make it easy to specify a specific version (i.e. a tag like `v1.3` or a branch like `master`).

**Comment by Scit** [comment]
I see. Thank you!
